# Generated by Django 3.2.15 on 2022-10-18 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djps_app', '0002_auto_20221018_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='category_id',
            new_name='category',
        ),
    ]
